### ISSUE TITLE
Images with demonstrated egg detections 

### ISSUE THREAD

**Issue by opensourcegrappler** [chickenpi/ChookEggCount#2]
Are these images required? The code that ran to conduct the detection is not included in the repository?

**Comment by chickenpi** [comment]
The code that I used to create these images is a bit of a quick hack using cv:MatchTemplate (OpenCV), and searching on a couple of different patterns. I was thinking that it would be worth showing where this has worked well, but also where it has failed badly. Happy to remove these images if they don't add value.
